// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntmtyrgidorjzfmcpuao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bXR5cmdpZG9yanpmbWNwdWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDkxNDcsImV4cCI6MjA2MzU4NTE0N30.dDoRcVDmMbTI0-Lbw9pCwjzYwwbGgkjYDqPHDgFS5gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);